### PR TITLE
better Input vars for better overrides

### PR DESCRIPTION
**Pull request by peshay**

### CODE REVIEW

**Comment by johncclayton** [comment]
I'll take a peek at this when I'm back next week, thanks!

**Comment by johncclayton** [comment]
Looks like </dict> is in there twice within the AdobeAIR.filewave recipe.  I presume that's not intended... when running with </dict> duplicated, I see this during the validation check...

bigair:AutoPkg johnc$ autopkg run FWTool.filewave
WARNING: plist error for /Users/johnc/Library/AutoPkg/RecipeRepos/com.github.peshay.filewave-1/AdobeAIR/AdobeAIR.filewave.recipe: Error Domain=NSCocoaErrorDomain Code=3840 "Encountered unexpected element at line 25 (plist can only include one object)" UserInfo={NSDebugDescription=Encountered unexpected element at line 25 (plist can only include one object), kCFPropertyListOldStyleParsingError=Error Domain=NSCocoaErrorDomain Code=3840 "Malformed data byte group at line 1; invalid hex" UserInfo={NSDebugDescription=Malformed data byte group at line 1; invalid hex}}
Processing FWTool.filewave...
WARNING: plist error for /Users/johnc/Library/AutoPkg/RecipeRepos/com.github.peshay.filewave-1/AdobeAIR/AdobeAIR.filewave.recipe: Error Domain=NSCocoaErrorDomain Code=3840 "Encountered unexpected element at line 25 (plist can only include one object)" UserInfo={NSDebugDescription=Encountered unexpected element at line 25 (plist can only include one object), kCFPropertyListOldStyleParsingError=Error Domain=NSCocoaErrorDomain Code=3840 "Malformed data byte group at line 1; invalid hex" UserInfo={NSDebugDescription=Malformed data byte group at line 1; invalid hex}}
Path to Admin Tool: /Applications/FileWave/FileWave Admin.app/Contents/MacOS/FileWave Admin

Can you please fix the source and re-submit the PR.  I will continue testing here.

**Comment by johncclayton** [comment]
I also would like to know why you moved fw_app_version out of the recipe processor and into the input section.

**Comment by peshay** [comment]
Have you already testet with defaults write? Do you need any help or is there anything I can test?

**Pull request closed without merging**
